export const TEAM_HASHTAGS: Readonly<Record<string, string>> = {
  'DUKE':  '#GoDuke',
  'UNC':   '#GoHeels',
  'UK':    '#BBN',        // Kentucky
  'KAN':   '#RockChalk',
  'GONZ':  '#GoZags',
  'HOU':   '#GoCoogs',
  'PURD':  '#BoilerUp',
  'TENN':  '#VolNation',
  'AUB':   '#WarEagle',
  'ARIZ':  '#BearDown',
  'MSU':   '#GoGreen',    // Michigan State
  'UCLA':  '#GoBruins',
  'CONN':  '#UConn',
  'NOVA':  '#NovaNation',
  'BAY':   '#SicEm',
  'TEX':   '#HookEm',
  'IND':   '#IUBB',
  'ISU':   '#Cyclones',
  'CREI':  '#GoJays',
  'MARQ':  '#MUBB',
  'XAV':   '#GoX',
  'SJU':   '#RedStorm',
  'TCU':   '#GoFrogs',
  'FLA':   '#GoGators',
  'ALA':   '#RollTide',
  'ORE':   '#GoDucks',
  'ILL':   '#Illini',
  'UVA':   '#GoHoos',
  'SC':    '#Gamecocks',
  'LSU':   '#GeauxTigers',
  'MEM':   '#GoTigersGo',
  'SMC':   '#GaelsRise',
  'SDSU':  '#AztecsMBB',
  'BYU':   '#GoCougs',
  'DAY':   '#GoFlyers',
  'USU':   '#GoAggies',
  'DRKE':  '#MVCHoops',
  'LIB':   '#RiseWithUs',
  'MCN':   '#GeauxPokes',
  'UNM':   '#GoLobos',
};
